import {
  AlertTriangle,
  Boxes,
  CheckCircle2,
  ClipboardCheck,
  Cog,
  DoorClosed,
  Factory,
  Forklift,
  HelpCircle,
  Home,
  MapPin,
  PackageCheck,
  RotateCcw,
  Scissors,
  ShieldAlert,
  Tractor,
  Truck,
  UserCheck,
  Users,
  Wind,
  Wrench,
} from "lucide-react";
import type { IconComponentMap } from "../types";

export const icons: IconComponentMap = {
  alert: AlertTriangle,
  boxes: Boxes,
  check: CheckCircle2,
  clipboard: ClipboardCheck,
  cog: Cog,
  door: DoorClosed,
  factory: Factory,
  forklift: Forklift,
  help: HelpCircle,
  home: Home,
  "map-pin": MapPin,
  "package-check": PackageCheck,
  rotate: RotateCcw,
  scissors: Scissors,
  "shield-alert": ShieldAlert,
  tractor: Tractor,
  truck: Truck,
  "user-check": UserCheck,
  users: Users,
  wind: Wind,
  wrench: Wrench,
};
